# Default values for reana.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# reana_hostname: reana.cern.ch
# `reana_hostname` should be set for third party integrations to work and for
# production deployments to be secure.

# `limited_privs` should be set to true on openshift/OKD systems where users lack
#    privileges to list nodes, create storage classes, etc.  `use_security_contexts` should be set to false on these systems as well.

limited_privs: false
use_security_contexts: true

debug:
  enabled: false
eos:
  enabled: false

shared_storage:
  backend: hostpath  # hostpath | cephfs | nfs | custom
  custom_class:  # only fill in for custom backend
  volume_size: 200
  access_modes: ReadWriteMany
  shared_volume_mount_path: "/var/reana"
  hostpath:
    root_path: "/var/reana"
  cephfs:
    provisioner: manila-provisioner
    type: "Geneva CephFS Testing"
    availability_zone: nova
    os_secret_name: os-trustee
    os_secret_namespace: kube-system
    cephfs_os_share_id: <cephfs-share-id>
    cephfs_os_share_access_id: <cephfs-share-access-id>

secrets:
  database: {}
  gitlab: {}
  cern:
    sso: {}
  reana: {}

# External database service configuration
db_env_config:
  REANA_DB_NAME: "reana"
  REANA_DB_PORT: "5432"
  # There are two more environment variables that should be set in order
  # to connect to a database:
  # REANA_DB_USERNAME: containing the database user name.
  # REANA_DB_PASSWORD: containing the password for the user previously set.
  # Both environment variables should be set inside a Kubernetes secret:
  # `[release-name]-db-secrets`

# REANA components configuration
components:
  reana_ui:
    enabled: true
    docs_url: http://docs.reana.io
    forum_url: https://forum.reana.io
    imagePullPolicy: IfNotPresent
    image: reanahub/reana-ui:0.8.0-alpha.1
  reana_db:
    enabled: true
    volume_size: 20
  reana_server:
    imagePullPolicy: IfNotPresent
    image: reanahub/reana-server:0.8.0-alpha.1
    environment:
      REANA_MAX_CONCURRENT_BATCH_WORKFLOWS: 30
      REANA_SCHEDULER_SECONDS_TO_WAIT_FOR_REANA_READY: 600
      REANA_SCHEDULER_SECONDS_RETRY_DELAY: 60
      REANA_USER_EMAIL_CONFIRMATION: true
    uwsgi:
      processes: 6
      threads: 4
  reana_workflow_controller:
    imagePullPolicy: IfNotPresent
    image: reanahub/reana-workflow-controller:0.8.0-alpha.1
    environment:
      SHARED_VOLUME_PATH: /var/reana
  reana_workflow_engine_cwl:
    image: reanahub/reana-workflow-engine-cwl:0.8.0-alpha.1
  reana_workflow_engine_yadage:
    image: reanahub/reana-workflow-engine-yadage:0.8.0-alpha.1
  reana_workflow_engine_serial:
    image: reanahub/reana-workflow-engine-serial:0.8.0-alpha.1
  reana_job_controller:
    image: reanahub/reana-job-controller:0.8.0-alpha.2

notifications:
  enabled: false
  email_config: {}
  system_status: "0 0 * * *"

# Accessing the cluster from outside world
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.entryPoints: "http,https"
    ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    # enable tls here if using a native controller instead of traefik
    enabled: false
    secretName:

# Permissions
serviceAccount:
  create: true
  name: reana

# Traefik's chart values.yaml
traefik:
  enabled: true
  rbac:
    enabled: true
  dashboard:
    enabled: true
  serviceType: NodePort
  service:
    nodePorts:
      http: 30080
      https: 30443
  ssl:
    enabled: true
    generateTLS: true

# rabbitmq subchart
rabbitmq:
  clustering:
    enabled:
      false
  rbac:
    create: false
  podSecurityContext:
    enabled: false
  auth:
    username: "test"
    password: "1234"
  nameOverride: "message-broker"
  persistence:
    enabled:
      false
  communityPlugins: "https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/3.8.9/rabbitmq_delayed_message_exchange-3.8.9-0199d11c.ez"
  plugins: "rabbitmq_delayed_message_exchange rabbitmq_consistent_hash_exchange"


# Quota
quota:
  disk_update: "0 3 * * *"  # everyday at 3am
